#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
