#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Restarting nginx directly
sudo service nginx restart

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# It's usually unnecessary to change ownership of /var/www/html
# unless you have specific reasons to do so
# sudo chown -R "$USER":"$USER" /var/www/html
# sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restarting nginx
# Using restart to ensure Nginx is properly started or restarted
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
