#!/usr/bin/env bash
# HTTP response contains a custom header (on web-01 and web-02)

#pdate packeage and make yes to all question
sudo apt-get update
sudo apt-get install -y

#creating index page
echo "Hello World!" > /var/www/html/index.html

#redirection
new_string="server_name _:\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creating eror page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

#custon HTTP header
sudo sed -i "/server_name _/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-enabled/default

#test
sudo nginx -t

#restart
sudo service nginx restart
